package com.example.myapplication.core.util

object AppStrings {
    object Auth {
        const val LOGIN = "Đăng nhập"
        const val REGISTER = "Đăng ký"
        const val DRAFT_POST_ERROR = "Bạn cần đăng nhập để tạo bài viết."
        const val POST_ERROR_FALLBACK = "Không thể đăng bài viết."
        const val LOGIN_SIGNUP = "Đăng nhập/Đăng ký"
        const val EMAIL_PLACEHOLDER = "Nhập email"
        const val PASSWORD_PLACEHOLDER = "Nhập mật khẩu"
        const val FORGOT_PASSWORD = "Quên mật khẩu?"
        const val REGISTER_TITLE = "Đăng ký tài khoản"
        const val BACK = "Quay lại"
        const val CONFIRM_CODE = "Xác nhận mã"
        const val RESET_PASSWORD = "Quên mật khẩu"
        const val NEW_PASSWORD = "Mật khẩu mới"
        const val PASSWORD_INVALID = "Mật khẩu chưa hợp lệ"
        const val ALREADY_HAVE_ACCOUNT = "Đã có tài khoản? Đăng nhập"
        const val DONT_HAVE_ACCOUNT = "Chưa có tài khoản? Đăng ký ngay"
        const val DONT_HAVE_ACCOUNT_REGISTER = "Tạo tài khoản ngay"
        const val SIGN_IN_WITH_GOOGLE = "Tiếp tục với Google"
        const val CHANGE_PASSWORD = "Đổi mật khẩu"
        const val INPUT_EMAIL_PROMPT = "Nhập email tài khoản. App sẽ kiểm tra email tồn tại rồi gửi email đặt lại mật khẩu. Sau đó bạn nhập mã oobCode trong link email."
        const val INPUT_EMAIL_PLACEHOLDER = "Nhập email của bạn"
        const val INPUT_PASSWORD_REPEATED = "Nhập lại mật khẩu"
        const val INPUT_RESET_PROMPT = "Mở email đặt lại mật khẩu, copy link hoặc riêng phần oobCode rồi dán vào đây."
        const val INPUT_RESET_PLACEHOLDER = "Nhập link email hoặc mã oobCode"
        const val PASSWORD_RESET_CONFIRMED = "Mã đã được xác nhận. Hãy tạo mật khẩu mới cho tài khoản."
        const val INPUT_PASSWORD_NEW = "Nhập mật khẩu mới"
        const val INPUT_PASSWORD_NEW_REPEATED = "Nhập lại mật khẩu mới"
        const val PASSWORD_RULE_LENGTH = "Từ 8 - 32 ký tự"
        const val PASSWORD_RULE_ALPHA_NUM = "Bao gồm chữ thường và số"
        const val PASSWORD_RULE_SPECIAL = "Bao gồm ký tự đặc biệt (!,$,@,%,...)"
        const val PASSWORD_RULE_UPPERCASE = "Có ít nhất 1 ký tự in hoa"
        const val GOOGLE_PLAY_SERVICES_ERROR = "Google Play Services chưa sẵn sàng trên thiết bị này. Hãy cập nhật Google Play Services hoặc dùng emulator có Play Store."
        const val GOOGLE_SIGN_IN_CANCELLED = "Bạn đã hủy đăng nhập Google."
        const val GOOGLE_SIGN_IN_ERROR = "Không thể đăng nhập Google."
        const val GOOGLE_WEB_CLIENT_MISSING = "Thiếu Google Web Client ID. Hãy cập nhật google_web_client_id trong strings.xml."
        const val GOOGLE_SIGN_IN_UNAVAILABLE = "Google Sign-In chưa sẵn sàng. Cần thêm Android OAuth client cho com.example.myapplication với SHA-1 debug trong Google Cloud/Firebase rồi tải lại google-services.json."
        const val PROCESSING = "Đang xử lý..."
        const val SENDING = "Đang gửi..."
        const val VERIFYING = "Đang kiểm tra..."
        const val CHANGING = "Đang đổi..."
        const val SEND_RESET_LINK = "Gửi email đặt lại mật khẩu"
    }

    object Community {
        const val PLACEHOLDER = "Bạn đang nghĩ gì?"
        const val SELECTED_FILE = "Tệp đã chọn"
        const val CLOSE = "Đóng"
        const val NEW_POST = "Bài viết mới"
        const val ADD_IMAGE = "Ảnh"
        const val ADD_VIDEO = "Video"
        const val POSTING = "Đang đăng..."
        const val POST_ACTION = "Đăng"
        const val DELETE_FILE = "Xóa tệp"
        const val FEATURED_POSTS = "Dòng bài viết nổi bật"
        const val EVENT_TAG_SUBTITLE = "Có sự kiện kèm tag"
        const val BACK = "Quay lại"
        const val PUBLIC_GROUP = "Nhóm công khai"
        const val MEMBERS_SUFFIX = " thành viên"
        const val NO_EVENT_POSTS = "Chưa có bài viết phù hợp."
        const val RECENT_TIME = "Vừa xong"
        const val MINUTES_AGO = "cách đây %d phút"
        const val HOURS_AGO = "cách đây %d giờ"
        const val DAYS_AGO = "cách đây %d ngày"
        const val VIDEO_NOT_READY = "Video chưa sẵn sàng"
        const val AUDIO_FILE = "Tệp ghi âm"
        const val AUDIO_PREVIEW = "Ghi âm"
        const val EXIT = "Thoát"
        const val SHARE_ACTION = "Chia sẻ"
        const val SHARE_NOW = "Chia sẻ ngay"
        const val FAVORITE = "Yêu thích %d"
        const val SHARES_COUNT = "%d lượt chia sẻ"
        const val NO_COMMENTS = "Chưa có bình luận."
        const val COMMENT_UNDER_NAME = "Bình luận dưới tên %s"
        const val WRITE_COMMENT_PLACEHOLDER = "Viết bình luận dưới tên %s..."
        const val SEND = "Gửi"
        const val WATCH_VIDEO = "Xem video"
        const val AUTH_REQUIRED_TITLE = "Yêu cầu đăng nhập"
        const val AUTH_REQUIRED_DESC = "Vui lòng đăng nhập để thích, bình luận, chia sẻ hoặc viết bài của riêng bạn."
        const val LATER = "Để sau"
        const val LOGIN = "Đăng nhập"
        const val YOU = "Bạn"
        const val INTERESTED = "Quan tâm"
        const val INTERESTED_COUNT = "+99 quan tâm"
        const val FLASH_SALE_TITLE = "Giảm chớp nhoáng"
        const val FLASH_SALE_SUB = "Flash Sale\nCuối Tuần!"
        const val FLASH_SALE_BODY = "Giảm giá lên đến 50% cho các sự kiện hot nhất tuần này."
        const val VIEW_NOW = "Xem ngay"
    }

    object Profile {
        const val LOGIN_SIGNUP = "Đăng nhập/Đăng ký"
        const val HELP_CENTER = "Trung tâm trợ giúp"
        const val HELP_CENTER_DESC = "Mở trung tâm trợ giúp"
        const val OPTIONS_TITLE = "Tùy chọn"
        const val ACCOUNT_SETTINGS = "Cài đặt tài khoản"
        const val ACCOUNT_INFO = "Thông tin tài khoản"
        const val NOTIFICATION_SETTINGS = "Cài đặt"
        const val LOGOUT = "Đăng xuất"
        const val BACK = "Quay lại"
        const val YOUR_POSTS = "Bài viết của bạn"
        const val NO_POSTS_SELF = "Bạn chưa tạo bài viết nào."
        const val NO_POSTS_OTHER = "%s chưa tạo bài viết nào."
        const val LIKES_SUFFIX = " thích"
        const val COMMENTS_SUFFIX = " bình luận"
        const val SHARES_SUFFIX = " chia sẻ"
        const val LIKES_STAT = "thích"
        const val FOLLOWERS_STAT = "Follower"
        const val FOLLOWING_STAT = "đã follow"
        const val FOLLOWED = "Đang follow"
        const val FOLLOW = "Follow"
        const val POSTS_OF_USER = "Bài viết của %s"
    }
}
